const constants = {
	ADD_SONG: "ADD_SONG",
	REMOVE_SONG: "REMOVE_SONG",
	EDIT_SONG: "EDIT_SONG",
	ADD_PERSON: "ADD_PERSON",
	REMOVE_PERSON: "REMOVE_PERSON",
	EDIT_PERSON: "EDIT_PERSON",
	ADD_SERVICE: "ADD_SERVICE",
	REMOVE_SERVICE: "REMOVE_SERVICE",
	EDIT_SERVICE: "EDIT_SERVICE",
	ADD_ERROR: "ADD_ERROR",
	CLEAR_ERROR: "CLEAR_ERROR",
}

export default constants